image: ghcr.io/preparingforexams/wheel-of-misfortune-backend:${GITHUB_SHA}
serviceAccount:
  json: ${GCP_SERVICE_ACCOUNT_JSON}
secret:
  internalToken: ${INTERNAL_API_KEY}
  wheelToken: ${WHEEL_TOKEN}
